### ISSUE TITLE
Renaming anything is not supported. Sorry. Use tab to autocomplete. Or you can use fish or oh my zsh which will also offes autocomplete full name.

### ISSUE THREAD

**Issue by Gamesgalor05** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#203] opened 2021-01-11 05:41 UTC
Renaming anything is not supported. Sorry. Use tab to autocomplete. Or you can use fish or oh my zsh which will also offes autocomplete full name.

_Originally posted by @fakeid30 in https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/issues/202#issuecomment-757417434_

I tried this but it still didn't work, I redownloaded the file, didnt rename anything and did the same steps to use it, but i am still getting that same error

**Comment by fakeid30** [comment] 2021-01-11 06:32
@Gamesgalor05 ok how have you tried running the program and what exactly was the problem ? 

Given how this has not occurred for most people I am inclined to say it's an user error. 

Write down the steps to reproduce the error. Follow the issue template please.

**Comment by Gamesgalor05** [comment] 2021-01-11 09:02
I already said it in the other thing. To reproduce it this what I did.
Download the zip file
Extract with "Extract here"
Move that file into the pi file
Open the terminal
cd "the name of this thing"
python requirements.py
python udemy_enroller.py --browser=chromium

but this error appears
  File "udemy_enroller.py", line 15
    browser: str,
                ^

**Comment by fakeid30** [comment] 2021-01-11 09:10
@cullzie are you aware of any bug in arm platform for this to happen ?

**Comment by Gamesgalor05** [comment] 2021-01-11 09:46
btw that arrow is supposed to point to the " : " but the spaces are gone for some reason

**Comment by cullzie** [comment] 2021-01-11 16:13
Not that I'm aware of. Is your python version python 3? Type `python` and see what it says at the top of the terminal it opens. You might just need to run `python3 udemy_enroller.py --browser=chromium`

**Comment by Gamesgalor05** [comment] 2021-01-11 23:21
pi@raspberrypi:~/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-master $ python3 udemy_enroller.py --browser=chromium
Traceback (most recent call last):
  File "udemy_enroller.py", line 8, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver
ModuleNotFoundError: No module named 'selenium'

Just to make sure this error wasn't me, I extracted the file again the did the same stuff but for used python3 udemy_enroller.py --browser=chromium

Not sure if this is progress. Btw I made sure that when running requirements.py I did see it say "Installed SELENIUM".

**Comment by fakeid30** [comment] 2021-01-12 05:29
@Gamesgalor05 you need to read each and every line of the readme and follow them.

You haven't installed the requirement.

I'm closing this issue. Any further query about this issue will be closed without reply. Since it's user error and not a software issue.

I advice you to reread the readme instead of wasting time writing issues.

**Closed by fakeid30** 2021-01-12 05:29 UTC
Labels: question
