### ISSUE TITLE
HIT THE CACHE 12 TIMES[BUG]

### ISSUE THREAD

**Issue by prokan468** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#155] opened 2020-12-11 20:34 UTC
When i run the command (**python udemy_enroller.py --browser=chrome**), the browser gets opened and udemy gets logged in, but then suddenly, the cmd starts throwing errors and at the end the browser gets closed with the message **"HIT THE CACHE 12 TIMES"**
Well, it did work for the first time when i tried it but then it didn't work after.

**Comment by fakeid30** [comment] 2020-12-11 20:35
This is intended behavior , it means there are no new courses at the time. Try again in 24 hours.

**Comment by prokan468** [comment] 2020-12-12 01:51
But.. it isnt possible... I didnt let the code scrape more than 1 page and it says this...

**Comment by fakeid30** [comment] 2020-12-12 05:58
@prokan468 can you record a screencast with a new account and post it here ? 

I can't reproduce your issue.

**Comment by cullzie** [comment] 2020-12-12 08:35
@prokan468 Can you please attach the relevent logs as well please? They should be in app.log file. Thanks

To increase the number of cache hits before exiting you can call the script like this `python udemy_enroller.py --browser=chrome --cache-hits=100`

**Comment by fakeid30** [comment] 2020-12-14 07:43
@prokan468 I think this is solved, but if you still have issue , try the develop version and if you still have issue, let us know via another comment. I am closing this now.

**Closed by fakeid30** 2020-12-14 07:43 UTC
Labels: bug, question
