### ISSUE TITLE
[BUG] Cloudflare Captcha not recognized

### ISSUE THREAD

**Issue by TheDebianGuy** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#238] opened 2021-02-11 11:02 UTC
**Describe the bug**
I downloaded this tool like a two weeks ago and it was working just fine, but today I heated it up and got cloudflare captcha instantly.

**To Reproduce**
Start it as you would normally and get captcha'd.

**Expected behavior**
It should wait as well as with the udemy built in google captcha.

**Screenshots**
![image](https://user-images.githubusercontent.com/64433908/107628207-99ec6a00-6c60-11eb-974b-298ff2d0d857.png)
This is how cloudflare captcha looks like

**Desktop (please complete the following information):**
 - latest win10 with latest chrome & chromedriver

**Additional context**
**Suggested solution** for the udemy_enroller/udemy.py
```
def _check_if_robot(self) -> bool:
        is_robot = True
        try:
            self.driver.find_element_by_id("px-captcha")
        except NoSuchElementException:
                try:
                    self.driver.find_element_by_id("cf-hcaptcha-container")
                except NoSuchElementException:
                    is_robot = False
        return is_robot
```
I downloaded the version from releases, so Im sorry if you already fixed this on the main branch or whatever github repo has.

~Regards Debian Guy

**Comment by cullzie** [comment] 2021-02-11 15:16
Ye the issue is documented here: #233

A fix to detect it has been released to the develop branch but the captcha still seems to be unsolvable

**Comment by fakeid30** [comment] 2021-02-12 04:20
@TheDebianGuy I'm closing this to track the issue on issue #233

**Closed** 2021-02-12 04:21 UTC
Labels: bug
