### ISSUE TITLE
[BUG] Error TutorialBar Scrapper Certificate Verify Failed...

### ISSUE THREAD

**Issue by jlarini** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#325] opened 2021-09-30 21:08 UTC
Hi...

This error starts to occur today:

"Error in get request: Cannot connect to host www.tutorialbar.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')]
Page: 1 of None scraped from tutorialbar.com"

maybe it occurred before...

Thanks.

**Comment by theqkash** [comment] 2021-10-01 02:00
It happens because of yesterday's changes with LetsEncrypt root certificate.

**Comment by cullzie** [comment] 2021-10-04 09:26
I am not seeing this error. Is it something that is still happening?

**Comment by fakeid30** [comment] 2021-10-04 09:37
@cullzie i can't reproduce this as well.

**Comment by theqkash** [comment] 2021-10-04 09:44
![image](https://user-images.githubusercontent.com/6078401/135829544-a8d97d24-5d59-4b8f-a757-620379b8914b.png)

For me still happening, however I'm using Windows - maybe that's why.

Problem is described here: https://letsencrypt.org/2021/10/01/cert-chaining-help.html

**Comment by cullzie** [comment] 2021-10-04 11:58
I think if we hit this error we could retry with the `ssl verify=False`. Might resolve then the second time

**Comment by rama-shankar** [comment] 2021-10-12 15:09
This change fixed my problem

**_\udemy_enroller\http.py_**

import aiohttp
import ssl
import certifi
from udemy_enroller.logging import get_logger

logger = get_logger()

sslcontext = ssl.create_default_context(cafile=certifi.where())

async def get(url, headers=None):
    """
    Send REST get request to the url passed in

    :param url: The Url to get call get request on
    :param headers: The headers to pass with the get request
    :return: data if any exists
    """
    if headers is None:
        headers = {}
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(url, headers=headers,ssl=sslcontext) as response:
                text = await response.read()
                return text
    except Exception as e:
        logger.error(f"Error in get request: {e}")

**Comment by cullzie** [comment] 2022-06-03 19:17
Closing as it doesn't appear to be reproducible.

**Closed by cullzie** 2022-06-03 19:17 UTC
Labels: bug
