### ISSUE TITLE
[BUG] (Unknown error) Unexpected exception: 'data-clp-course-id'

### ISSUE THREAD

**Issue by owlg** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#249] opened 2021-02-24 00:23 UTC
I was running the program the first time, not sure how this error comes about.

I used the alpha branch code as the main branch is not giving enough time for me to solve the captcha before automatically closing the program. 

**To Reproduce**
Run the program with scraping "https://discudemy.com" enabled (getting 0 links), and some courses already enrolled. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6251538/108926458-728e9780-7679-11eb-8cfa-91be8e67f777.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Using Alpha Branch (program runs on CLI)

**Additional context**

**Comment by owlg** [comment] 2021-02-24 16:56
Furthermore, the script scrapes but is not enrolling into courses that are not already enrolled.

**Comment by ruipcf** [comment] 2021-02-25 01:22
I'm having the same error.

**Comment by cullzie** [comment] 2021-02-27 00:55
I cannot reproduce this on my system. Do you get this everytime you run?

**Comment by cullzie** [comment] 2021-02-27 01:08
If you are always seeing it can you please replace this [line](https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/blob/alpha/udemy_enroller/udemy.py#L300) in the code with the following:
```
        html_body = soup.find("body")
        if html_body.get("data-clp-course-id") is not None:
            return int(html_body["data-clp-course-id"])
        else:
            logger.debug(f"Body: {html_body}")
            raise ValueError("Cannot get course id")
```

Can you run in debug mode and post the results back here. Thanks

**Comment by ruipcf** [comment] 2021-02-27 09:02
This is only part of the output, if I need to I can publish the entire output! Thanks


Got 12 links from https://www.tutorialbar.com in 3.26 seconds
Checkout failed: https://www.udemy.com/course/sap-c_tscm66_66-associate-logistics-and-warehouse-exam/
Checkout payload: {'checkout_event': 'Submit', 'shopping_cart': {'items': [{'discountInfo': {'code': 'C_TSCM66'}, 'purchasePrice': {'amount': 0, 'currency': 'EUR', 'price_string': 'Free', 'currency_symbol': '€'}, 'buyableType': 'course', 'buyableId': 3849582, 'buyableContext': {}}], 'is_cart': True}, 'payment_info': {'payment_vendor': 'Free', 'payment_method': 'free-method'}}
In cache: https://www.udemy.com/course/css-made-simple-for-beginners-learn-to-style-a-website-page/?couponCode=B7C5729A3B90EAC3E91B
Checkout failed: https://www.udemy.com/course/learn-advanced-sql-for-oracle-databases/
Checkout payload: {'checkout_event': 'Submit', 'shopping_cart': {'items': [{'discountInfo': {'code': 'F9AF6E8A10949F69EA1C'}, 'purchasePrice': {'amount': 0, 'currency': 'EUR', 'price_string': 'Free', 'currency_symbol': '€'}, 'buyableType': 'course', 'buyableId': 653954, 'buyableContext': {}}], 'is_cart': True}, 'payment_info': {'payment_vendor': 'Free', 'payment_method': 'free-method'}}
Checkout failed: https://www.udemy.com/course/jquery-for-beginners-a-basic-introduction/
Checkout payload: {'checkout_event': 'Submit', 'shopping_cart': {'items': [{'discountInfo': {'code': '0043F5EB2FD3AA33258B'}, 'purchasePrice': {'amount': 0, 'currency': 'EUR', 'price_string': 'Free', 'currency_symbol': '€'}, 'buyableType': 'course', 'buyableId': 651780, 'buyableContext': {}}], 'is_cart': True}, 'payment_info': {'payment_vendor': 'Free', 'payment_method': 'free-method'}}
In cache: https://www.udemy.com/course/html-canvas-for-absolute-beginners/?couponCode=D4155EEF709F97446D2D

**Comment by cullzie** [comment] 2021-03-04 18:57
@ruipcf Thanks for the logs. Unfortunately they don't give much insight into what the problem is here. I'll see if I can reproduce this somewhere. 
Out of interest when you login is your account in Euro currency?

**Comment by ruipcf** [comment] 2021-03-05 10:46
It's in dollars.
I tried creat a new account on udemy and the script works fine so maybe it's some problem with my personal account although I can purchase new courses in the first account by writing the discount codes by myself.

**Comment by cullzie** [comment] 2021-03-05 14:22
@ruipcf Ok that sounds like the issue then.
The script is not using your currency but instead its getting it from wherever you are calling the api from.
So if you are a US dollar registered user but you are running the script in France it is incorrectly passing Euro as your currency.
I'll try put in a fix for this and you can test it out.

**Closed** 2021-03-17 04:22 UTC
Labels: bug
