### ISSUE TITLE
Stuck at payment checkout!

### ISSUE THREAD

**Issue by No08** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#46] opened 2020-10-12 18:40 UTC
After collecting all the links with coupon codes, the program goes to udemy and select enroll, which is problematic because there should be a verification system whether adding the coupon makes the course "free" or not. There are some coupons which lessens the price. The bot also clicks there and gets stuck at payment process. This keeps happening and everytime it happens it throws an error like "find_all of none" type. Then I have to restart the bot again. I think you can add the verification process like when the "Buy Now" text is available in the "udlite-btn udlite-btn-large udlite-btn-primary udlite-heading-md styles--btn--express-checkout--28jN4" classes, the bot skips the page and go to the next link. Please look into it. Thanks!

**Comment by fakeid30** [comment] 2020-10-13 08:42
This is a good idea, thanks.

**Comment by ethankrein** [comment] 2020-10-13 16:13
I've never encountered that exception, but I am familiar with the script attempting to redeem courses that aren't completely free.

Instead of checking the buy now text I would probably check price to see if it's $0. 

This also solves for another issue that we discuss in the readme: `clear all saved Debit/Credit Card or any other saved payment info from your Browser & your Udemy account before using the script.` The user will not have to clear that data if we simply don't attempt to redeem paid courses.

**Comment by fakeid30** [comment] 2020-11-06 10:53
@cullzie Is this issue fixed ? I can't reproduce.

**Comment by cullzie** [comment] 2020-11-06 15:25
@fakeid30 I haven't seen this particular issue. 

Maybe it can be updated to be about better error handling and logging in the the scripts.

First step would be to add proper logging to file. This makes reporting bugs more straightforward for the user.

Then better error handling to log common issues:
- Robot Check error
- Already Enrolled error
- Invalid coupon error (When course is not free)
- Unkown Error (Please send report with logs)

**Comment by fakeid30** [comment] 2020-11-06 15:30
Perfect, thanks for the explanation.

**Comment by fakeid30** [comment] 2020-11-09 14:56
@No08 fixed by PR #92 

Use develop branch if you need it now.

**Closed by fakeid30** 2020-11-09 14:56 UTC
Labels: enhancement, good first issue, help wanted
