### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tkossak** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#343] opened 2021-11-03 19:13 UTC
**Describe the bug**
I ran `udemy_enroller` and got error:
```
Loading existing settings
Loading cookies from file
Exception in redeem courses: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.
```

**To Reproduce**
run `udemy_enroller`

**Expected behavior**
I have no idea - just ran it for the first time

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Browser: the tool didn't start any brwoser
 - Version: of what? udemy_enroller doesn't even have `--version` option (but i just installed it using pipx, so probably it's latest)

**Comment by cullzie** [comment] 2021-11-09 15:54
Hi @tkossak I'm going to close this as a duplicate of #327 
The REST based login has stopped working. There is a working replacement on alpha branch that uses selenium if you want to check it out.

**Closed** 2021-11-09 15:54 UTC
Labels: bug
