### ISSUE TITLE
[BUG] Even after typing "python udemy_enroller.py --browser=chrome --cache-hits=1000 --max-pages=10" the browser closed after 3 pages and given below error

### ISSUE THREAD

**Issue by biswajit1602** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#186] opened 2020-12-24 11:03 UTC
Moving on to the next page of the course list on tutorialbar.com
```
Please Wait: Getting the course list from tutorialbar.com...
Page: 4 of 653 scraped
Closing browser
Traceback (most recent call last):
  File "C:\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE\udemy_enroller.py", line 77, in <module>
    run(args.browser, args.max_pages, args.cache_hits)
  File "C:\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE\udemy_enroller.py", line 33, in run
    redeem_courses(driver, settings, max_pages, cache_hit_limit)
  File "C:\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE\core\utils.py", line 113, in redeem_courses
    _redeem_courses(driver, settings, max_pages, cache_hit_limit)
  File "C:\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE\core\utils.py", line 42, in _redeem_courses
    udemy_course_links = tb_scraper.run()
  File "C:\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE\core\tutorialbar.py", line 38, in run
    udemy_links = self.gather_udemy_course_links(course_links)
  File "C:\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE\core\tutorialbar.py", line 127, in gather_udemy_course_links
    results = thread_pool.map(self.get_udemy_course_link, courses)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE\core\tutorialbar.py", line 114, in get_udemy_course_link
    response = requests.get(url=url)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by fakeid30** [comment] 2020-12-24 11:13
Thanks for the report . Will investigate.

**Comment by cullzie** [comment] 2020-12-24 11:26
@fakeid30 Think this is related to the issue just fixed with the non-latin urls. It was creating too many redirects causing the error.
@biswajit1602 Can you checkout the develop branch and see if the issue is resolved?

**Comment by biswajit1602** [comment] 2020-12-24 11:33
sure checking it now

**Comment by biswajit1602** [comment] 2020-12-24 11:39
It's showing
PS C:\Users\Admin\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-74fd4f8a0efefcd3b3ba5ee12a57164a4075ba8c> python udemy_enroller.py --browser=chrome --cache-hits=1000 --max-pages=10
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-74fd4f8a0efefcd3b3ba5ee12a57164a4075ba8c\udemy_enroller.py", line 6, in <module>
    from core import ALL_VALID_BROWSER_STRINGS, DriverManager, Settings
  File "C:\Users\Admin\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-74fd4f8a0efefcd3b3ba5ee12a57164a4075ba8c\core\__init__.py", line 4, in <module>
    from .scrapers.manager import ScraperManager
  File "C:\Users\Admin\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-74fd4f8a0efefcd3b3ba5ee12a57164a4075ba8c\core\scrapers\manager.py", line 5, in <module>
    from core.scrapers.comidoc import ComidocScraper
  File "C:\Users\Admin\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-74fd4f8a0efefcd3b3ba5ee12a57164a4075ba8c\core\scrapers\comidoc.py", line 5, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**Comment by cullzie** [comment] 2020-12-24 11:44
@biswajit1602 The requirements have been updated on develop branch so you will need to pip install the requirements.txt again before proceeding.

**Comment by biswajit1602** [comment] 2020-12-24 12:24
Well, its fixed now. And its superfast enrolling. Great job Guys. You people are awesome

**Comment by cullzie** [comment] 2020-12-24 12:33
Thanks for checking @biswajit1602
We appreciate all the compliments :smile:

**Closed** 2020-12-24 12:35 UTC
Labels: bug
