### ISSUE TITLE
Error: [Command errored out with exit status 1] Can someone explains the error.

### ISSUE THREAD

**Issue by jacob-lawrence-2** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#309] opened 2021-08-20 19:15 UTC
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-gxr5hm53\\brotlipy_feb442f80cd2428bb5e4a5ff23c3d2b6\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-gxr5hm53\\brotlipy_feb442f80cd2428bb5e4a5ff23c3d2b6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-y_o5dcy8\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\brotlipy'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-gxr5hm53\brotlipy_feb442f80cd2428bb5e4a5ff23c3d2b6\
    Complete output (12 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\brotli
    copying src\brotli\brotli.py -> build\lib.win-amd64-3.9\brotli
    copying src\brotli\build.py -> build\lib.win-amd64-3.9\brotli
    copying src\brotli\__init__.py -> build\lib.win-amd64-3.9\brotli
    running build_clib
    building 'libbrotli' library
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-gxr5hm53\\brotlipy_feb442f80cd2428bb5e4a5ff23c3d2b6\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-gxr5hm53\\brotlipy_feb442f80cd2428bb5e4a5ff23c3d2b6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-y_o5dcy8\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\brotlipy' Check the logs for full command output.

**Comment by x-garcia** [comment] 2021-08-21 04:18
Duplicate of #295

**Comment by fakeid30** [comment] 2021-08-30 08:48
@x-garcia thank you

@jacob-lawrence-2 see the related issue and it's solution.

**Closed by fakeid30** 2021-08-30 08:48 UTC
Labels: question
