### ISSUE TITLE
[BUG] ZipCode

### ISSUE THREAD

**Issue by Mercyfulsin** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#188] opened 2020-12-27 22:46 UTC
When going to purchase a course, the program clicks purchase before it can ever enter a zipcode.

**To Reproduce**
Run using chromium browser and watch as the zipcode is not entered.

**Expected behavior**
It should enter the zipcode but there is no pause for it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium
 - Version: 87.0.4280

**Additional context**
Adding a simple ```Sleep(1)``` to Core/udemy.py below line 150.
![temp](https://user-images.githubusercontent.com/16928058/103181119-46f65900-4852-11eb-9bd2-8c9f48195274.png)

**Comment by fakeid30** [comment] 2020-12-28 06:25
https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/issues/157

This is a duplicate of this bug, pulling from develop should fix it.

**Closed by fakeid30** 2020-12-28 06:25 UTC
Labels: bug, duplicate
