### ISSUE TITLE
Microsoft Edge on Linux does not work (wrong download URL of the webdriver)

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#110] opened 2020-11-25 07:19 UTC
Relevant Error log : 

```
✖ 130 Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE git:(master) ✗ ❯❯❯ python udemy_enroller_edge.py 
Loading existing settings
[WDM] - There is no [linux64] edgedriver for browser  in cache
[WDM] - Trying to download new driver from https://msedgedriver.azureedge.net/87.0.664.47/edgedriver_linux64.zip
Traceback (most recent call last):
  File "udemy_enroller_edge.py", line 12, in <module>
    driver = webdriver.Edge(EdgeChromiumDriverManager().install())
  File "/home/nirjhor/.local/lib/python3.8/site-packages/webdriver_manager/microsoft.py", line 47, in install
    return self._get_driver_path(self.driver)
  File "/home/nirjhor/.local/lib/python3.8/site-packages/webdriver_manager/manager.py", line 29, in _get_driver_path
    file = download_file(driver.get_url())
  File "/home/nirjhor/.local/lib/python3.8/site-packages/webdriver_manager/utils.py", line 93, in download_file
    validate_response(response)
  File "/home/nirjhor/.local/lib/python3.8/site-packages/webdriver_manager/utils.py", line 79, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://msedgedriver.azureedge.net/87.0.664.47/edgedriver_linux64.zip

```

**Comment by cullzie** [comment] 2020-11-25 18:31
@fakeid30 Ye the resource is gone by the looks of it.
This would be a bug on the webdriver-manager tool we use: https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/microsoft.py#L35-L36

**Comment by fakeid30** [comment] 2020-11-26 05:50
I filed an issue there.

**Comment by cullzie** [comment] 2020-11-26 21:21
Changed the label to wont fix as its outside our control until a fix is released for this: https://github.com/SergeyPirogov/webdriver_manager/issues/162

**Comment by cullzie** [comment] 2020-12-16 09:16
That link seems to be working now but for that version of edge there is no driver available for linux. Can you try it again and see if its working now?

**Comment by fakeid30** [comment] 2020-12-16 10:41
I'll test tomorrow and update you on this

**Comment by fakeid30** [comment] 2020-12-17 07:47
@cullzie 

```
◆ Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE git:(master) ❯❯❯ python udemy_enroller.py --browser=edge
Loading existing settings
[WDM] - There is no [linux64] edgedriver for browser  in cache
[WDM] - Trying to download new driver from https://msedgedriver.azureedge.net/87.0.664.60/edgedriver_linux64.zip
Traceback (most recent call last):
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller.py", line 77, in <module>
    run(args.browser, args.max_pages, args.cache_hits)
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller.py", line 31, in run
    dm = DriverManager(browser=browser, is_ci_build=settings.is_ci_build)
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/driver_manager.py", line 37, in __init__
    self._init_driver()
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/driver_manager.py", line 57, in _init_driver
    self.driver = webdriver.Edge(EdgeChromiumDriverManager().install())
  File "/home/nirjhor/.local/lib/python3.9/site-packages/webdriver_manager/microsoft.py", line 47, in install
    return self._get_driver_path(self.driver)
  File "/home/nirjhor/.local/lib/python3.9/site-packages/webdriver_manager/manager.py", line 29, in _get_driver_path
    file = download_file(driver.get_url())
  File "/home/nirjhor/.local/lib/python3.9/site-packages/webdriver_manager/utils.py", line 93, in download_file
    validate_response(response)
  File "/home/nirjhor/.local/lib/python3.9/site-packages/webdriver_manager/utils.py", line 79, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://msedgedriver.azureedge.net/87.0.664.60/edgedriver_linux64.zip

```

**Comment by cullzie** [comment] 2020-12-17 09:37
Maybe it is to do with the version  of edge you have installed on your system. Anyway I don't think the issue is with the `web_driver_manager` library but more that MS don't ship a edge driver for linux on every release

**Comment by fakeid30** [comment] 2020-12-17 11:27
> Maybe it is to do with the version of edge you have installed on your system. Anyway I don't think the issue is with the `web_driver_manager` library but more that MS don't ship a edge driver for linux on every release

it could be .

**Closed** 2021-02-14 05:05 UTC
Labels: wontfix
